-- 0019_phrase_tier.sql — utility tier for phrase candidate ordering.
-- Source: words/phrases.csv tier column (T1=142 highest-utility everyday phrases, T2, T3;
-- see words/PHRASE_METHODOLOGY.md). The tier was dropped at original seeding, leaving phrase
-- candidates in pure insertion order — a T2 phrase could be among the first met (beta report
-- 44a3116c). getDueBatch's phraseCandidates now orders by tier ASC NULLS LAST, created_at, id.
-- Backfill matches on the exact target text; rows deleted from the CSV (the 13 single-word
-- duplicates) or added later simply keep tier NULL and sort last.

alter table public.phrases add column if not exists tier smallint;

update public.phrases p set tier = v.tier
from (values
  ('Vienu kafiju, lūdzu.', 1),
  ('Vienu tēju, lūdzu.', 1),
  ('Ūdeni, lūdzu.', 1),
  ('Es gribētu kafiju.', 1),
  ('Es gribētu kaut ko ēst.', 1),
  ('Vai jums ir tēja?', 1),
  ('Vai es varu dabūt kafiju?', 1),
  ('Karti, lūdzu.', 1),
  ('Vai es varu redzēt karti?', 1),
  ('Cik tā ir cena?', 1),
  ('Man garšo.', 1),
  ('Galdu diviem, lūdzu.', 2),
  ('Vai šeit ir brīvs galds?', 2),
  ('Vai es varu šeit apsēsties?', 2),
  ('Vēl vienu kafiju, lūdzu.', 2),
  ('Es gribētu alu.', 2),
  ('Vienu vīnu, lūdzu.', 2),
  ('Vai jums ir kāds dzēriens?', 2),
  ('Vai jūs varat man iedot ūdeni?', 2),
  ('Vai jums ir kāds ēdiens?', 3),
  ('Es vēlētos pudeli ūdens.', 3),
  ('Paldies, viss bija ļoti labs.', 3),
  ('Vai es varu paņemt karti?', 3),
  ('Vai es varu vēl dabūt tēju?', 3),
  ('Es gribētu pusdienas.', 2),
  ('Cik es esmu jums parādā?', 3),
  ('Es nesaprotu.', 1),
  ('Atvainojiet, es nesaprotu.', 1),
  ('Vai varat vēlreiz pateikt?', 1),
  ('Vēlreiz, lūdzu.', 1),
  ('Lūdzu, runājiet lēni.', 1),
  ('Vai varat runāt lēnāk?', 2),
  ('Es runāju tikai mazliet.', 1),
  ('Es vēl mācos.', 1),
  ('Ko tas nozīmē?', 1),
  ('Ko šis vārds nozīmē?', 2),
  ('Es nezinu.', 1),
  ('Es nezinu šo vārdu.', 1),
  ('Atvainojiet?', 1),
  ('Piedodiet, es nedzirdēju.', 2),
  ('Vienu mirkli.', 1),
  ('Vienu mirklīti, lūdzu.', 2),
  ('Pagaidiet, lūdzu.', 2),
  ('Tagad saprotu.', 2),
  ('Tagad ir skaidrs.', 2),
  ('Es nesaprotu šo vārdu.', 2),
  ('Vai varat to pateikt vēlreiz?', 2),
  ('Es nesaprotu, ko jūs sakāt.', 3),
  ('Vai varat parādīt?', 3),
  ('Es nezinu, kā to pateikt.', 3),
  ('Vai jūs mani saprotat?', 2),
  ('Atvainojiet, kur ir stacija?', 1),
  ('Kā es tieku uz centru?', 1),
  ('Kā man tikt līdz viesnīcai?', 1),
  ('Kur ir tuvākais autobuss?', 1),
  ('Pa kreisi vai pa labi?', 1),
  ('Ej pa kreisi.', 1),
  ('Tad pa labi.', 1),
  ('Vai tas ir tālu?', 1),
  ('Nē, tas ir pavisam tuvu.', 1),
  ('Kur es varu nopirkt biļeti?', 1),
  ('Cik ir biļetes cena?', 1),
  ('Vai šis autobuss brauc uz centru?', 1),
  ('Kurš vilciens brauc uz pilsētu?', 1),
  ('Vai tu vari man parādīt kartē?', 2),
  ('Parādiet, lūdzu, kartē.', 2),
  ('Es esmu pazudis.', 2),
  ('Es nezinu, kur es esmu.', 2),
  ('Vai šī ir pareizā iela?', 2),
  ('Ej uz priekšu.', 2),
  ('Tas ir aiz stūra.', 2),
  ('Tas ir blakus bankai.', 2),
  ('Kurš ir tuvākais ceļš uz tirgu?', 3),
  ('Vai es varu aiziet ar kājām?', 3),
  ('Vai šeit apstājas autobuss?', 3),
  ('Kur ir izeja?', 3),
  ('Vai tev ir karte?', 3),
  ('Man jāiet uz veikalu.', 1),
  ('Man vajag uz banku.', 1),
  ('Vai veikals ir vaļā?', 1),
  ('Vai jūs jau esat ciet?', 1),
  ('Cikos jūs beidzat?', 1),
  ('Cikos jūs atverat?', 1),
  ('Man tas ir vajadzīgs.', 1),
  ('Man vajag tikai vienu lietu.', 1),
  ('Es drīz būšu atpakaļ.', 1),
  ('Es tūlīt atgriezīšos.', 1),
  ('Man jāiet uz darbu.', 1),
  ('Es esmu mājās.', 1),
  ('Es esmu darbā.', 1),
  ('Es aizmirsu.', 1),
  ('Man šodien ir tikšanās ar ārstu.', 2),
  ('Man jāiet pie ārsta.', 2),
  ('Cikos ir tikšanās?', 2),
  ('Man jānopērk nedaudz ēdiena.', 2),
  ('Vai te var nopirkt zāles?', 2),
  ('Es aizmirsu maku mājās.', 2),
  ('Man nav naudas.', 2),
  ('Vai jums ir mana karte?', 2),
  ('Es eju uz pilsētas centru.', 2),
  ('Pagaidi mani te, es tūlīt nākšu.', 3),
  ('Cik ilgi jūs vēl esat vaļā?', 3),
  ('Man vēl jānokārto dažas lietas.', 3),
  ('Veikals jau ir ciet.', 3),
  ('Man ir labi.', 1),
  ('Man ir slikti.', 1),
  ('Es jūtos labi.', 1),
  ('Es jūtos slikti.', 1),
  ('Viss kārtībā.', 1),
  ('Es esmu laimīgs.', 1),
  ('Es esmu priecīgs.', 1),
  ('Man nav labi.', 2),
  ('Es neesmu priecīgs.', 2),
  ('Es gribu ēst.', 1),
  ('Es gribu dzert.', 1),
  ('Es gribu gulēt.', 2),
  ('Es vairs nevaru.', 2),
  ('Es esmu slims.', 1),
  ('Es jūtos slims.', 2),
  ('Man sāp.', 1),
  ('Man sāp šeit.', 1),
  ('Man sāp galva.', 2),
  ('Man sāp zobs.', 2),
  ('Man sāp mugura.', 2),
  ('Man vajag ārstu.', 1),
  ('Lūdzu, izsauciet ārstu.', 2),
  ('Man vajag uz slimnīcu.', 2),
  ('Es uztraucos.', 1),
  ('Neuztraucies.', 2),
  ('Drīz kļūsti vesels!', 1),
  ('Es ceru, ka tev būs labāk.', 2),
  ('Man ir bail.', 2),
  ('Tagad man ir labāk.', 2),
  ('Man ir liels prieks.', 3),
  ('Kā tev iet?', 1),
  ('Kā jums iet?', 1),
  ('Kā jūs jūtaties?', 2),
  ('Labi, paldies!', 1),
  ('Liels paldies!', 1),
  ('Paldies par palīdzību!', 2),
  ('Nav par ko!', 1),
  ('Atvainojiet!', 1),
  ('Atvaino!', 1),
  ('Piedod!', 1),
  ('Piedodiet!', 1),
  ('Man ļoti žēl.', 2),
  ('Jā, protams!', 1),
  ('Uz redzēšanos!', 1),
  ('Uz drīzu tikšanos!', 2),
  ('Tiekamies!', 2),
  ('Tiekamies rīt!', 2),
  ('Prieks iepazīties!', 1),
  ('Ļoti patīkami!', 2),
  ('Laipni lūdzam!', 3),
  ('Šis ir mans draugs.', 1),
  ('Šī ir mana draudzene.', 1),
  ('Vai tu gribi atnākt?', 1),
  ('Vai gribi iet kopā?', 1),
  ('Uz redzēšanos rīt!', 1),
  ('Atnāc pie manis!', 1),
  ('Ko tu šodien dari?', 1),
  ('Es esmu aizņemts.', 1),
  ('Es esmu aizņemta.', 1),
  ('Varbūt vēlāk.', 1),
  ('Tas izklausās labi.', 1),
  ('Paldies par piedāvājumu!', 1),
  ('Vai tev šodien ir laiks?', 2),
  ('Satiksimies šovakar?', 2),
  ('Vai gribi iedzert kafiju?', 2),
  ('Nāc pie mums!', 2),
  ('Lieliska ideja!', 2),
  ('Man tas ļoti patīk.', 2),
  ('Diemžēl es nevaru.', 2),
  ('Šodien nevaru, bet varbūt rīt.', 2),
  ('Cikos tiekamies?', 2),
  ('Vai vari atnākt vakarā?', 2),
  ('Es priecājos tevi redzēt!', 2),
  ('Sen neredzēti!', 3),
  ('Vai vari rīt atnākt pie manis?', 3),
  ('Varam satikties pilsētā.', 3),
  ('Paldies, ka atnāci!', 3),
  ('Labi, tad tiekamies vēlāk.', 3),
  ('Nāc, parunāsim!', 3),
  ('Cik tas?', 1),
  ('Cik ir cena?', 1),
  ('Tas ir par dārgu.', 1),
  ('Tas ir dārgs.', 1),
  ('Tas nav dārgs.', 2),
  ('Es gribu šo nopirkt.', 1),
  ('Es to gribu nopirkt.', 1),
  ('Es vēlos to nopirkt.', 2),
  ('Vai jums ir...?', 1),
  ('Vai jums tas ir?', 2),
  ('Vai es varu ar karti?', 1),
  ('Man ir tikai nauda.', 2),
  ('Lūk, lūdzu.', 2),
  ('Es tikai skatos.', 1),
  ('Somu, lūdzu.', 1),
  ('Vai jums ir soma?', 2),
  ('Kuru?', 1),
  ('Kuru jūs gribat?', 2),
  ('Šo, lūdzu.', 1),
  ('To, lūdzu.', 1),
  ('Es gribu šo.', 2),
  ('Vai es varu paskatīties?', 2),
  ('Vai jūs varat to parādīt?', 2),
  ('Es to ņemu.', 2),
  ('Es to paņemšu.', 3),
  ('Es meklēju dāvanu.', 3),
  ('Kā iet?', 1),
  ('Man iet labi.', 1),
  ('Labi, paldies, un tev?', 1),
  ('Paldies, labi. Un jums?', 1),
  ('Nu, viss labi.', 2),
  ('Man iet diezgan labi.', 2),
  ('Šodien man iet ļoti labi.', 2),
  ('Man iet slikti.', 3),
  ('No kurienes tu esi?', 1),
  ('No kurienes jūs esat?', 1),
  ('Es esmu no Latvijas.', 2),
  ('Kā tevi sauc?', 1),
  ('Kā jūs sauc?', 1),
  ('Mani sauc Anna.', 1),
  ('Mans vārds ir Anna.', 2),
  ('Šodien ir jauks laiks.', 1),
  ('Šodien ir skaists laiks.', 2),
  ('Laiks ir slikts.', 2),
  ('Ārā ir saule.', 2),
  ('Ārā ir liels vējš.', 2),
  ('Kā pagāja tava diena?', 2),
  ('Kā pagāja jūsu diena?', 2),
  ('Mana diena pagāja labi.', 2),
  ('Kas jauns?', 2),
  ('Cik ir pulkstenis?', 1),
  ('Cik pulkstenis?', 2),
  ('Pulkstenis ir divi.', 1),
  ('Tagad ir pieci.', 1),
  ('Pulksten desmit.', 1),
  ('Tiekamies pulksten septiņos.', 2),
  ('Cikos mēs tiekamies?', 1),
  ('Šodien man nav laika.', 1),
  ('Man ir laiks.', 1),
  ('Man nav laika.', 1),
  ('Vienu minūti!', 1),
  ('Tikai vienu minūti.', 1),
  ('Es nāku tūlīt.', 1),
  ('Es atnākšu vēlāk.', 1),
  ('Drīz būšu klāt.', 1),
  ('Rīt man ir laiks.', 1),
  ('Vakar man nebija laika.', 2),
  ('Kad tu vari?', 1),
  ('Kad mēs tiekamies?', 1),
  ('Kura diena tev der?', 2),
  ('Tiekamies rīt no rīta.', 1),
  ('Tiekamies vakarā.', 1),
  ('Šorīt man nav laika.', 2),
  ('Šovakar es esmu brīvs.', 2),
  ('Šodien es esmu aizņemts.', 2),
  ('Cik ilgi tas būs?', 2),
  ('Pulkstenis ir jau vēls.', 3),
  ('Vai tev tagad ir laiks?', 2)
) as v(target, tier)
where p.target = v.target;
